### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by HomeFiber** [Ax6/Fast-F1#2]
Hi, how can I graph all the laps between two drivers on the same tire? For example, if I want the graph of all the laps and relative times and speeds between Vettel and Hamilton with SOFT rubber, what should I write in the program?

Thanks so much

**Comment by Ax6** [comment]
It depends on what laps are you looking for. But in case you were to plot the fastest lap on Soft compound you can write the following

```
import sys
import fastf1 as ff1
from fastf1 import plotting
from matplotlib import pyplot as plt

quali_session = ff1.get_session(2019, 'Silverstone', 'Q')
laps = quali_session.load_laps()
soft_laps = laps.pick_tyre('SOFT')
vettel_laps = soft_laps.pick_driver('VET')
hamilton_laps = soft_laps.pick_driver('HAM')
best_vettel = vettel_laps.pick_fastest()
best_hamilton = hamilton_laps.pick_fastest()

fig, ax = plt.subplots()
ax.plot(best_vettel.telemetry['Space'], best_vettel.telemetry['Speed'])
ax.plot(best_hamilton.telemetry['Space'], best_hamilton.telemetry['Speed'])
plt.show()
```

At the moment there is no built-in method to plot delta time (I will work on that).
For now you will need to add a few more steps. In particular you want to interpolate time and space so that you can subtract the two time signals. Something similar to this...

```
import numpy as np

space_reference = np.arange(0, reference_telemetry['Space'].max())
interp_time1 = np.interp(space_reference, telemetry1['Space'], telemetry1['Time']) 
interp_time2 = np.interp(space_reference, telemetry2['Space'], telemetry2['Time'])
delta_time = interp_time1 - interp_time2
```

**Comment by Ax6** [comment]
The delta time utility has been added https://ax6.github.io/Fast-F1/utils.html#fastf1.utils.delta_time
